name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codestyle:
    name: codestyle
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.x'
          architecture: 'x64'

      - name: Install Poetry and dependencies
        uses: SneaksAndData/github-actions/install_poetry@v0.0.19
        with:
          install_extras: all

      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'codestyle'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        env:
          PROJECT_NAME: esd_services_api_client
        run: |
          set -euxo pipefail
          find "$PROJECT_NAME" -type f -name "*.py" | xargs poetry run pylint

      - name: Black
        run: |
          set -euxo pipefail
          poetry run black . --check --diff

